### ISSUE TITLE
dataset tree api response time is too long.

### ISSUE THREAD

**Issue by HuangLuGuang** [OpenCSGs/csghub-server#140]
This repository only has a 1.2G CSV file，The Api normally times out. I changed the timeout threshold.
<img width="1721" alt="image" src="https://github.com/user-attachments/assets/6a0dc72a-6013-4c1d-a423-b03283b481d1">

**Comment by Rader** [comment]
thanks for report this issue.
please follow the issue template to add extra info like version, env etc

**Comment by pulltheflower** [comment]
@HuangLuGuang Did you track this csv file by `git lfs`?

**Comment by HuangLuGuang** [comment]
> @HuangLuGuang Did you track this csv file by `git lfs`?

your are right, thang you!
