### ISSUE TITLE
goland Ide本地编译错误

### ISSUE THREAD

**Issue by xian952777** [OpenCSGs/csghub-server#215]
![Uploading 1734508123223.png…]()

**Comment by xian952777** [comment]
# opencsg.com/csghub-server/cmd/csghub-server
D:\code\go\pkg\mod\golang.org\toolchain@v0.0.1-go1.23.4.windows-amd64\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:\msys64\ucrt64\bin\gcc.exe -m64 -mconsole -Wl,--tsaware -Wl,--nxcompat -Wl,--major-os-version=6 -Wl,--minor-os-version=1 -Wl,--major-subsystem-version=6 -Wl,--minor-subsystem-version=1 -Wl,--dynamicbase -Wl,--high-entropy-va -o $WORK\b001\exe\a.out.exe -Wl,--no-insert-timestamp C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\go.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000000.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000001.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000002.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000003.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000004.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000005.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000006.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000007.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000008.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000009.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000010.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000011.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000012.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000013.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000014.o C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000015.o -O2 -g -O2 -g -Wl,-T,C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\fix_debug_gdb_scripts.ld -Wl,--start-group -lmingwex -lmingw32 -Wl,--end-group -lkernel32
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\WSN\AppData\Local\Temp\go-link-4093329112\000002.o: in function `_cgo_e932c59bbd46_Cfunc_duckdb_append_data_chunk':
/tmp/go-build/cgo-gcc-prolog:56:(.text+0x1b): undefined reference to `__imp_duckdb_append_data_chunk'

**Comment by Rader** [comment]
On windows, the correct version of gcc and the neccesary runtime libraries needs to be installed. See this doc:
https://github.com/marcboeker/go-duckdb?tab=readme-ov-file#windows
