### ISSUE TITLE
服务无法重启

### ISSUE THREAD

**Issue by mdllly** [OpenCSGs/csghub-server#60]
服务关机后无法重启，一直卡在：
[root@localhost all_in_one]# docker logs 166aee40504a
Waiting for Gitea service to be ready...

需要删掉启动目录下gitdata,gitlogs,在执行启动才能成功，但是此操作数据会丢失。

**Comment by Rader** [comment]
“服务关机”是指正常的 stop 了 service吗？“关机”之前做了哪些操作？

> Waiting for Gitea service to be ready..
这个日志是说 gitea 服务无法访问，可以查看一下 gitea 的服务日志

**Comment by mdllly** [comment]
正常stop后关闭服务器，在进入执行重启也是报同样的错

**Comment by Rader** [comment]
未收到回复，先关闭 issue
